server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdai?useSSL=false&autoReconnect=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true