spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdai?useSSL=false&autoReconnect=true&characterEncoding=utf8&&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

mybatis-plus:
  type-aliases-package: org.maxwell.mybatis.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    map-underscore-to-camel-case: true
    log-impl:
      org:
        apache:
          ibatis:
            logging:
              stdout: StdOutImpl


